### ISSUE TITLE
cannot compile the test npc and debug npc

### ISSUE THREAD

**Issue by diancangyun** [Pychnight/Custom-Npcs#13]
oh.the custom npc need testnpc.dll and debugnpc.dll.
but when I user the source at visul studio and try to compile,
it can not be compile and ton of error.
result ,the compile dll is smaller than your release dll.
can you help me.
i like this plugin.
thank you

**Comment by Pychnight** [comment]
Well, your probably missing the Tshock DLL's also when you try to compile make sure you choose "TShock" instead of OTA without the exact errors. there is not much, i can do..
